[package]
name = "minimal"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.81"

[lib]
crate-type = ["dylib"]

[dependencies]
reth-exex-plugin = { version = "0.0", path = "../.." }
